# Generated by Django 3.1 on 2020-08-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genere',
            new_name='genre',
        ),
    ]
